### ISSUE TITLE
pretrain code

### ISSUE THREAD

**Issue by zjn0613** [noorahmedds/OrCo#3]
Hello, after training the miniimagenet solo code, the results when loading into ORCO are quite low. Could you provide a complete miniImagenet training code?

**Comment by dongdongswd** [comment]
> Hello, after training the miniimagenet solo code, the results when loading into ORCO are quite low. Could you provide a complete miniImagenet training code?

Hello, have you solved it now? Could you tell me how to do pre-training？

**Comment by zjn0613** [comment]
> > Hello, after training the miniimagenet solo code, the results when loading into ORCO are quite low. Could you provide a complete miniImagenet training code?
> 
> Hello, have you solved it now? Could you tell me how to do pre-training？

It’s still not solved, but the author has updated the base training `.sh` script, so you can try again!
